blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('tags/<slug:slug>/', views.tags),
    path('<slug:pk>/', views.article),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('signup/', views.signup),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('blog/', include('blog.urls')),
    path('mypage/', views.MypageView.as_view()),
    path('contact/', views.ContacView.as_view()),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Tag(models.Model):
    slug = models.CharField(primary_key=True, unique=True, max_length=20)
    name = models.CharField(unique=True, max_length=20)

    def __str__(self):
        return self.slug

class Article(models.Model):
    title      = models.CharField(default="", max_length=30)
    text       = models.TextField(default="")
    author     = models.CharField(default="", max_length=30)
    count      = models.IntegerField(default=0)
    tags       = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

class Comment(models.Model):
    comment    = models.TextField(default="", max_length=500)
    created_at = models.DateField(auto_now_add=True)
    user       = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    article    = models.ForeignKey(Article, on_delete=models.CASCADE)

mysite/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email     = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin  = models.BooleanField(default=False)
    objects   = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email     = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin  = models.BooleanField(default=False)
    objects   = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

# -- OneToOneFieldsを同時に作成 --
from django.db.models.signals import post_save
from django.dispatch import receiver
from mysite.models.profile_models import Profile

@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])
# -- OneToOneFieldsを同時に作成 --

mysite/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
	user       = models.OneToOneField(get_user_model(), unique=True, on_delete=models.CASCADE, primary_key=True)
	username   = models.CharField(default="匿名ユーザー", max_length=30)
	zipcode    = models.CharField(default="", max_length=8)
	prefecture = models.CharField(default="", max_length=6)
	city       = models.CharField(default="", max_length=50)
	address    = models.CharField(default="", max_length=200)

mysite/forms.py
from django import forms
from django.contrib.auth import get_user_model
from mysite.models.profile_models import Profile

class UserCreationForm(forms.ModelForm):
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('email',)

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'username',
            'zipcode',
            'prefecture',
            'city',
            'address',
        )

mysite/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from mysite.forms import UserCreationForm, ProfileForm
from blog.models import Article
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
import os

def index(request):
    ranks = Article.objects.order_by('-count')[:2]
    articles = Article.objects.all()[:3]
    context = {
        'title': 'Django Brog Site',
        'articles': articles,
        'ranks': ranks,
	}
    return render(request, 'mysite/index.html', context)

class Login(LoginView):
    template_name = 'mysite/auth.html'

    def form_valid(self, form):
        messages.success(self.request, 'ログインが完了しました！')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'ログインに失敗しました！')
        return super().form_invalid(form)

def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # user.is_active = False
            user.save()
            login(request, user) # 登録後にログインさせる
            messages.success(request, '登録が完了しました！')
            return redirect('/')
    return render(request, 'mysite/auth.html', context)

class MypageView(LoginRequiredMixin, View):
    context = {}

    def get(self, request):
        return render(request, 'mysite/mypage.html', self.context)

    def post(self, request):
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, '登録完了しました')
        return render(request, 'mysite/mypage.html', self.context)

class ContacView(View):
    context = {}

    def get(self, request):
        return render(request, 'mysite/contact.html', self.context)

    def post(self, request):
        subject = 'お問い合わせがありました'
        message = "お問い合わせがありました。\n名前: {}\nメールアドレス: {}\n内容: {}".format(request.POST.get('name'), request.POST.get('email'), request.POST.get('content'))
        email_from = os.environ['DEFAULT_EMAIL_FROM']
        email_to = [os.environ['DEFAULT_EMAIL_FROM'],]
        send_mail(subject, message, email_from, email_to)
        return render(request, 'mysite/contact.html', self.context)

templates/mysite/auth.html
{% extends 'mysite/base_auth.html' %}

{% block content %}

<div class="container ">
  <div class="row">
    <div class="col-lg-3 m-auto ">
      <h1 class="display-4 font-italic text-center "><a href="/" class="text-decoration-none">ReallySite</a></h1>
    </div>
    <div class="col-lg-3 m-auto ">
      <form class="form-signin mx-4" method="POST">

        {% csrf_token %}

        <div class="text-center">

          <h1 class="h5 my-4 ">
            {% if 'login' in request.path %}
            ログイン
            {% elif 'signup' in request.path %}
            新規登録
            {% endif %}
          </h1>

        </div>
        <div class="form-label-group my-3">
          <input type="email" id="id_email" name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}" class="form-control" placeholder="Email address" required autofocus>
        </div>
        <div class="form-label-group my-3">
          <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
        </div>
        <button class="btn btn-primary btn-block my-3" type="submit">サインイン</button>
      </form>

      {% if 'login' in request.path %}
      <div class="text-center">
        <a href="/signup/" class="link-secondary">新規登録はこちら</a>
      </div>
      {% elif 'signup' in request.path %}
      <div class="text-center">
        <a href="/login/" class="link-secondary">ログインはこちら</a>
      </div>
      {% endif %}

    </div>
  </div>
</div>

{% endblock %}

templates/mysite/base.html
<!DOCTYPE html>
<html lang="js">
  <head>
    {% include 'mysite/snippets/head.html' %}
  </head>
  <body>
    {% include 'mysite/snippets/header.html' %}
    {% include 'mysite/snippets/messages.html' %}

    {% block content %}
    {% endblock %}

    {% include 'mysite/snippets/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  </body>
</html>

templates/mysite/base_auth.html
<!DOCTYPE html>
<html lang="js">
  <head>
    {% include 'mysite/snippets/head.html' %}
  </head>
  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">

    {% block content %}
    {% endblock %}

  </body>
</html>

templates/mysite/contact.html
{% extends 'mysite/base.html' %}

{% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 font-italic border-bottom">お問い合わせ</h3>
      <form class="row g-3" method="POST">
        {% csrf_token %}
        <div class="col-12">
          <label class="form-label">名前</label>
          <input type="text" class="form-control" id="id_name" name="name">
        </div>
        <div class="col-12">
          <label class="form-label">メールアドレス</label>
          <input type="email" class="form-control" id="id_email" name="email">
        </div>
        <div class="col-12">
          <label class="form-label">お問い合わせ内容</label>
          <textarea class="form-control" id="id_content" name="content" rows="4"></textarea>
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </form>
    </div>

    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>
{% endblock %}

templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% block content %}

<div class="container">
  <div class="p-4 p-md-5 mb-4 rounded bg-warning">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Django講座</h1>
      <p class="lead my-3">サンプル...</p>
      <p class="lead mb-0">
        <a href="#" class="font-weight-bold">続きを読む</a>
      </p>
    </div>
  </div>

  <div class="row mb-2">
    {% for rank in ranks %}
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Django</strong>
          <h3 class="mb-0">{{ rank.title }}</h3>
          <div class="mb-1 text-muted">{{ rank.created_at }}</div>
          <p class="card-text mb-auto">{{ rank.text }}</p>
          <a href="/blog/{{ rank.id }}/" class="stretched-link">続きを読む</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 font-italic border-bottom">Django Lesson</h3>

      {% for article in articles %}
      <div class="blog-post">
        <h2 class="blog-post-title">{{ article.title }}</h2>
        <p class="blog-post-meta">
          {{ article.created_at }} by
          <a href="/blog/{{ article.id }}">{{ article.author }}</a>
        </p>
        <p>{{ article.text }}</p>
        <a href="/blog/{{ article.id }}">続きはこちら</a>
      </div>
      <hr>
      {% endfor %}

      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="/blog/">ブログ一覧はこちら</a>
      </nav>
    </div>

    {% include 'mysite/snippets/sidebar.html' %}

  </div>
</main>

{% endblock %}

templates/mysite/login.html
{% extends 'mysite/base_auth.html' %}

{% block content %}

<div class="container ">
  <div class="row">
    <div class="col-lg-3 m-auto ">
      <h1 class="display-4 font-italic text-center "><a href="/" class="text-decoration-none">ReallySite</a></h1>
    </div>
    <div class="col-lg-3 m-auto ">
      <form class="form-signin mx-4" method="POST">

        {% csrf_token %}

        <div class="text-center">
          <h1 class="h5 my-4 ">ログイン</h1>
        </div>
        <div class="form-label-group my-3">
          <input type="email" id="id_email" name="username" class="form-control" placeholder="Email address" required autofocus>
        </div>
        <div class="form-label-group my-3">
          <input type="password" id="id_password" name="password" class="form-control" placeholder="Password" required>
        </div>
        <button class="btn btn-primary btn-block my-3" type="submit">サインイン</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/mysite/mypage.html
{% extends 'mysite/base.html' %}

{% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 font-italic border-bottom">マイページ</h3>
      <form class="row g-3" method="POST">
        {% csrf_token %}
        <div class="col-12">
          <label class="form-label">ユーザー名（公開されます）</label>
          <input type="text" class="form-control" id="id_username" name="username" placeholder="煉獄 杏寿郎" value="{{ user.profile.username }}">
        </div>
        <div class="col-md-2">
          <label class="form-label">郵便番号</label>
          <input type="text" class="form-control" id="id_zipcode" name="zipcode" value="{{ user.profile.zipcode }}">
        </div>
        <div class="col-md-4">
          <label class="form-label">都道府県</label>
          <select id="id_prefecture" name="prefecture" class="form-select" value="">
            <option selected>選択...</option>
            <option>...</option>
          </select>
        </div>
        <div class="col-md-6">
          <label class="form-label">市区</label>
          <input type="text" class="form-control" id="id_city" name="city" value="{{ user.profile.city }}">
        </div>
        <div class="col-12">
          <label class="form-label">住所</label>
          <input type="text" class="form-control" id="id_address" name="address" placeholder="" value="{{ user.profile.address }}">
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-success">保存</button>
        </div>
      </form>
    </div>

    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>
{% endblock %}